// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	//CreateAppUser
	//
	//  INSERT INTO app_user(username)
	//  VALUES ($1)
	//  RETURNING guid, username, created_at, deleted_at
	CreateAppUser(ctx context.Context, username string) (AppUser, error)
	//CreateAppUserProfile
	//
	//  INSERT INTO app_user_profile(
	//      app_user_guid,
	//      name,
	//      surname,
	//      patronymic,
	//      nickname,
	//      bio,
	//      profile_discovery,
	//      avatar_url
	//  ) VALUES (
	//      $1, $2, $3, $4, $5, $6, $7, $8
	//  )
	//  RETURNING app_user_guid, name, surname, patronymic, nickname, bio, profile_discovery, avatar_url, editing_locked_at, created_at, deleted_at
	CreateAppUserProfile(ctx context.Context, arg CreateAppUserProfileParams) (AppUserProfile, error)
}

var _ Querier = (*Queries)(nil)
