// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/ReallyWeirdCat/brainiac/internal/domain/enum"
	"github.com/google/uuid"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_user(username)
VALUES ($1)
RETURNING guid, username, created_at, deleted_at
`

// CreateAppUser
//
//	INSERT INTO app_user(username)
//	VALUES ($1)
//	RETURNING guid, username, created_at, deleted_at
func (q *Queries) CreateAppUser(ctx context.Context, username string) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser, username)
	var i AppUser
	err := row.Scan(
		&i.Guid,
		&i.Username,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAppUserProfile = `-- name: CreateAppUserProfile :one
INSERT INTO app_user_profile(
    app_user_guid,
    name,
    surname,
    patronymic,
    nickname,
    bio,
    profile_discovery,
    avatar_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING app_user_guid, name, surname, patronymic, nickname, bio, preferred_language, profile_discovery, avatar_url, editing_locked_at, created_at, deleted_at
`

type CreateAppUserProfileParams struct {
	AppUserGuid      uuid.UUID                 `db:"app_user_guid" json:"app_user_guid"`
	Name             *string                   `db:"name" json:"name"`
	Surname          *string                   `db:"surname" json:"surname"`
	Patronymic       *string                   `db:"patronymic" json:"patronymic"`
	Nickname         *string                   `db:"nickname" json:"nickname"`
	Bio              *string                   `db:"bio" json:"bio"`
	ProfileDiscovery enum.ProfileDiscoveryEnum `db:"profile_discovery" json:"profile_discovery"`
	AvatarUrl        *string                   `db:"avatar_url" json:"avatar_url"`
}

// CreateAppUserProfile
//
//	INSERT INTO app_user_profile(
//	    app_user_guid,
//	    name,
//	    surname,
//	    patronymic,
//	    nickname,
//	    bio,
//	    profile_discovery,
//	    avatar_url
//	) VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8
//	)
//	RETURNING app_user_guid, name, surname, patronymic, nickname, bio, preferred_language, profile_discovery, avatar_url, editing_locked_at, created_at, deleted_at
func (q *Queries) CreateAppUserProfile(ctx context.Context, arg CreateAppUserProfileParams) (AppUserProfile, error) {
	row := q.db.QueryRow(ctx, createAppUserProfile,
		arg.AppUserGuid,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Nickname,
		arg.Bio,
		arg.ProfileDiscovery,
		arg.AvatarUrl,
	)
	var i AppUserProfile
	err := row.Scan(
		&i.AppUserGuid,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Nickname,
		&i.Bio,
		&i.PreferredLanguage,
		&i.ProfileDiscovery,
		&i.AvatarUrl,
		&i.EditingLockedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
